language: python

python: 3.4

cache:
  directories:
    - $HOME/.cache/pip

install:
    - make requirements-tests
    - pip install coveralls

script: 
    - make test

after_success:
    - coveralls
