language: python

python: 
    - 3.4
    - 3.5

cache:
  directories:
    - $HOME/.cache/pip

install:
    - make requirements-test
    - pip install coveralls

script: 
    - make test

after_success:
    - coveralls
